server:
  #端口号
  port: 10008
spring:
  application:
    ##当前服务名
    name: eureka-peer

eureka:
  instance:
    hostname: dev1
  client:
    #檢索服務
    fetch-registry: false
    #是否将自己注冊到eureka
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10008/eureka
  server:
    ###当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    ##自我保护机制
    enable-self-preservation: true
    ###eureka多长时间更新一次数据
    peer-eureka-nodes-update-interval-ms: 100000